### ISSUE TITLE
Core UI: enhancement of Form components

### ISSUE THREAD

**Issue by MaJoHo** [BEXIS2/bexis2-core-ui#38]
- rename DprodownKVP to since there is no other type of Dprodown. Maybe the same for Checkbox. (skipped)
- [x] cositent neming for parameters e.g. Dropdown the prameter is "targetIsComplex" in Multiselect "isTargetComplex"
- [x] feature pairety for components of nerly same kind or where it would be useful  e.G. Dropdown and Multiselect. Dropdown has itemId and label (itemLabel is better i think) missing.

**Comment by DavidBlaa** [comment]
- simple dropdown will come
- complexTarget & complexSource
