### ISSUE TITLE
Duplicate IDs in core components

### ISSUE THREAD

**Issue by zxyctn** [BEXIS2/bexis2-core-ui#65]
Some examples discovered:
- Units in the table have same "edit" ID for edit buttons, "delete" for delete buttons.
- The `div` for description shares the "description" ID with the `textarea` inside of it.

**Comment by geofranzi** [comment]
https://github.com/BEXIS2/bexis2-core-ui/commit/5b9f8d6b89db01af8f91903abf25f24460e45331
